### ISSUE TITLE
Dont require Reboot for Userland plugins,

### ISSUE THREAD

**Issue by KuromeSan** [ONElua/AutoPlugin2#31]
for user plugins (except those that load on SceShell) a reboot is not acturally required. all that needs to be done is the "reload config.txt" button in henkaku settings or just call taiReloadConfig();

also you could LoadStartModule on kernel plugins, leaving reboot only for SceShell ..

**Comment by Yoti** [comment]
It works anyway.

**Comment by DevDavisNunez** [comment]
We actually did a full reboot of the console, because there are very few plugins, even in user that do not require a full reboot like the user (SceShell), but hey, in the last  [release 1.04](https://github.com/ONElua/AutoPlugin2/releases/tag/1.04)  we added the possibility that the extremely few plugins that weren't require full reboot of the console, they will not and will only reload tai.
